[package]
name = "rustic_raytracer"
version = "0.1.0"
authors = ["Bjørn Grønbæk <github@gronbaek.net>"]
edition = "2018"

[dependencies]
euclid = "0.19.5"
image = "*"
float-cmp = "0.4.0"
rand = "0.6.5"